from qdarktheme.qtpy.QtCore import QAbstractTableModel as QAbstractTableModel, QModelIndex as QModelIndex, Qt as Qt
from qdarktheme.qtpy.QtGui import QIcon as QIcon, QTextOption as QTextOption
from qdarktheme.qtpy.QtWidgets import QCheckBox as QCheckBox, QComboBox as QComboBox, QDateTimeEdit as QDateTimeEdit, QDial as QDial, QGridLayout as QGridLayout, QGroupBox as QGroupBox, QLCDNumber as QLCDNumber, QLabel as QLabel, QLineEdit as QLineEdit, QListWidget as QListWidget, QProgressBar as QProgressBar, QPushButton as QPushButton, QRadioButton as QRadioButton, QScrollArea as QScrollArea, QSlider as QSlider, QSpinBox as QSpinBox, QSplitter as QSplitter, QTabWidget as QTabWidget, QTableView as QTableView, QTextEdit as QTextEdit, QToolBox as QToolBox, QToolButton as QToolButton, QTreeWidget as QTreeWidget, QTreeWidgetItem as QTreeWidgetItem, QVBoxLayout as QVBoxLayout, QWidget as QWidget
from typing import Any

class _Group1(QGroupBox):
    def __init__(self) -> None: ...

class _Group2(QGroupBox):
    def __init__(self) -> None: ...

class _TableModel(QAbstractTableModel):
    def __init__(self) -> None: ...
    def data(self, index: QModelIndex, role: int) -> Any: ...
    def rowCount(self, index) -> int: ...
    def columnCount(self, index) -> int: ...
    def flags(self, index: QModelIndex) -> Qt.ItemFlag: ...
    def headerData(self, section: int, orientation: Qt.Orientation, role: int = ...) -> Any: ...

class _Group3(QGroupBox):
    def __init__(self) -> None: ...

class _Group4(QGroupBox):
    def __init__(self) -> None: ...

class WidgetsUI:
    def setup_ui(self, win: QWidget) -> None: ...
