from _typeshed import Incomplete
from eyed3.utils.log import initLogging as initLogging

DEFAULT_PLUGIN: str
DEFAULT_CONFIG: Incomplete
USER_PLUGINS_DIR: Incomplete
DEFAULT_CONFIG_DEPRECATED: Incomplete
USER_PLUGINS_DIR_DEPRECATED: Incomplete

def main(args, config): ...
def profileMain(args, config): ...
def setFileScannerOpts(arg_parser, default_recursive: bool = ..., paths_metavar: str = ..., paths_help: str = ...) -> None: ...
def makeCmdLineParser(subparser: Incomplete | None = ...): ...
def parseCommandLine(cmd_line_args: Incomplete | None = ...): ...
