from PySide6.QtWidgets import *
from PyQt6.QtWidgets import *
from PyQt5.QtWidgets import *
from PySide2.QtWidgets import *
from collections.abc import Sequence
from qdarktheme.qtpy.QtCore import Qt as Qt
from qdarktheme.qtpy.QtGui import QPalette as QPalette
from qdarktheme.qtpy.qt_compat import QT_API as QT_API

class Application(QApplication):
    def __init__(self, args: Sequence[str] = ...) -> None: ...
    def exec(self) -> int: ...
    def exit(self, returnCode: int = ...) -> None: ...
    def setStyleSheet(self, sheet: str) -> None: ...
    def setAttribute(self, attribute: Qt.ApplicationAttribute, on: bool = ...) -> None: ...
    def setPalette(self, palette: QPalette, className: str = ...) -> None: ...
QApplication = Application
