from _typeshed import Incomplete
from eyed3 import core as core, utils as utils
from eyed3.utils import formatSize as formatSize, guessMimetype as guessMimetype
from eyed3.utils.console import Fore as Fore, HEADER_COLOR as HEADER_COLOR, boldText as boldText, printError as printError, printMsg as printMsg
from eyed3.utils.log import getLogger as getLogger

log: Incomplete

def load(name: Incomplete | None = ..., reload: bool = ..., paths: Incomplete | None = ...): ...

class Plugin(utils.FileHandler):
    SUMMARY: str
    DESCRIPTION: str
    NAMES: Incomplete
    arg_parser: Incomplete
    arg_group: Incomplete
    def __init__(self, arg_parser) -> None: ...
    args: Incomplete
    config: Incomplete
    def start(self, args, config) -> None: ...
    def handleFile(self, f) -> None: ...
    def handleDone(self) -> None: ...

class LoaderPlugin(Plugin):
    audio_file: Incomplete
    def __init__(self, arg_parser, cache_files: bool = ..., track_images: bool = ...) -> None: ...
    def handleFile(self, f, *args, **kwargs) -> None: ...
    def handleDirectory(self, d, _) -> None: ...
    def handleDone(self) -> None: ...
