from _typeshed import Incomplete
from eyed3.plugins import LoaderPlugin as LoaderPlugin

class PyModulePlugin(LoaderPlugin):
    SUMMARY: str
    DESCRIPTION: Incomplete
    NAMES: Incomplete
    def __init__(self, arg_parser) -> None: ...
    def start(self, args, config) -> None: ...
    def handleFile(self, f) -> None: ...
    def handleDirectory(self, d, _) -> None: ...
    def handleDone(self) -> None: ...
