from _typeshed import Incomplete

class AlbumMethods:
    def album(self, album_id, text_format: Incomplete | None = ...): ...
    def albums_charts(self, time_period: str = ..., chart_genre: str = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def album_comments(self, album_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def album_cover_arts(self, album_id, text_format: Incomplete | None = ...): ...
    def album_leaderboard(self, album_id, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def album_tracks(self, album_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
