from _typeshed import Incomplete

class AnnotationMethods:
    def annotation(self, annotation_id, text_format: Incomplete | None = ...): ...
    def annotation_edits(self, annotation_id, text_format: Incomplete | None = ...): ...
    def annotation_comments(self, annotation_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
