from _typeshed import Incomplete

class ArtistMethods:
    def artist(self, artist_id, text_format: Incomplete | None = ...): ...
    def artist_activity(self, artist_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def artist_albums(self, artist_id, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def artist_contribution_opportunities(self, artist_id, per_page: Incomplete | None = ..., next_curosr: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def artist_followers(self, artist_id, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def artist_leaderboard(self, artist_id, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def artist_songs(self, artist_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., sort: str = ...): ...
    def search_artist_songs(self, artist_id, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ..., sort: str = ...): ...
