from _typeshed import Incomplete

class ArticleMethods:
    def article(self, article_id, text_format: Incomplete | None = ...): ...
    def article_comments(self, article_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def latest_articles(self, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
