from _typeshed import Incomplete

class DiscussionMethods:
    def discussion(self, discussion_id, text_format: Incomplete | None = ...): ...
    def discussions(self, page: Incomplete | None = ...): ...
    def discussion_replies(self, discussion_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
