from _typeshed import Incomplete

class LeaderboardMethods:
    def leaderboard(self, time_period: str = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def charts(self, time_period: str = ..., chart_genre: str = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ..., type_: str = ...): ...
