from _typeshed import Incomplete

class MiscMethods:
    def line_item(self, line_item_id, text_format: Incomplete | None = ...): ...
    def page_data(self, album: Incomplete | None = ..., song: Incomplete | None = ..., artist: Incomplete | None = ...): ...
    def voters(self, annotation_id: Incomplete | None = ..., answer_id: Incomplete | None = ..., article_id: Incomplete | None = ..., comment_id: Incomplete | None = ...): ...
