from _typeshed import Incomplete

class ReferentMethods:
    def referent(self, referent_ids, text_format: Incomplete | None = ...): ...
    def referents(self, song_id: Incomplete | None = ..., web_page_id: Incomplete | None = ..., created_by_id: Incomplete | None = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def referents_charts(self, time_period: str = ..., chart_genre: str = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
