from _typeshed import Incomplete

class SearchMethods:
    def search(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ..., type_: str = ...): ...
    def search_albums(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_articles(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_artists(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_lyrics(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_songs(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_users(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_videos(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
    def search_all(self, search_term, per_page: Incomplete | None = ..., page: Incomplete | None = ...): ...
