from _typeshed import Incomplete

class SongMethods:
    def song(self, song_id, text_format: Incomplete | None = ...): ...
    def song_activity(self, song_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def song_comments(self, song_id, per_page: Incomplete | None = ..., page: Incomplete | None = ..., text_format: Incomplete | None = ...): ...
    def song_contributors(self, song_id): ...
