from _typeshed import Incomplete

class VideoMethods:
    def video(self, video_id, text_format: Incomplete | None = ...): ...
    def videos(self, album_id: Incomplete | None = ..., article_id: Incomplete | None = ..., song_id: Incomplete | None = ..., video_id: Incomplete | None = ..., per_page: Incomplete | None = ..., page: Incomplete | None = ..., series: bool = ...): ...
