from _typeshed import Incomplete
from genius.trie import TrieTree as TrieTree
from genius.word import Word as Word

here: Incomplete
library_path: Incomplete

class ResourceLoader:
    def __new__(cls, *args, **kwargs): ...
    def load_crf_seg_model(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_crf_pos_model(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_trie_tree(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_idf_table(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_break_table(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_break_regex_method(self, path: Incomplete | None = ..., force: bool = ...): ...
    def load_combine_regex_method(self, path: Incomplete | None = ..., force: bool = ...): ...
