from _typeshed import Incomplete

class TreeNode:
    value: Incomplete
    children: Incomplete
    def __init__(self) -> None: ...

class TrieTree:
    root: Incomplete
    def __init__(self) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def get(self, key): ...
    def add(self, key, value) -> None: ...
    def search(self, key): ...
