from _typeshed import Incomplete
from genius.tools import StringHelper as StringHelper

class Word:
    string_helper: Incomplete
    text: Incomplete
    freq: Incomplete
    tagging: Incomplete
    source: Incomplete
    offset: Incomplete
    def __init__(self, text, **kwargs) -> None: ...
    @property
    def marker(self): ...
    def __len__(self): ...
    def __hash__(self): ...
    def __eq__(self, obj): ...
