from _typeshed import Incomplete

MAX_INT16: Incomplete
MIN_INT16: Incomplete

def bytes2bin(bites, sz: int = ...): ...
def bin2bytes(x): ...
def bin2dec(x): ...
def bytes2dec(bites, sz: int = ...): ...
def dec2bin(n, p: int = ...): ...
def dec2bytes(n, p: int = ...): ...
def bin2synchsafe(x): ...
def bytes2signedInt16(bites: bytes): ...
def signedInt162bytes(n: int): ...
