from ..utils import safe_unicode as safe_unicode
from .base import BaseEntity as BaseEntity
from _typeshed import Incomplete

class Artist(BaseEntity):
    songs: Incomplete
    num_songs: Incomplete
    api_path: Incomplete
    header_image_url: Incomplete
    image_url: Incomplete
    is_meme_verified: Incomplete
    is_verified: Incomplete
    name: Incomplete
    url: Incomplete
    def __init__(self, client, json_dict) -> None: ...
    def __len__(self): ...
    def add_song(self, new_song, verbose: bool = ..., include_features: bool = ...): ...
    def song(self, song_name): ...
    def to_dict(self): ...
    def to_json(self, filename: Incomplete | None = ..., sanitize: bool = ..., ensure_ascii: bool = ...): ...
    def to_text(self, filename: Incomplete | None = ..., sanitize: bool = ...): ...
    def save_lyrics(self, filename: Incomplete | None = ..., extension: str = ..., overwrite: bool = ..., ensure_ascii: bool = ..., sanitize: bool = ..., verbose: bool = ...): ...
