from _typeshed import Incomplete
from lyricsgenius.utils import sanitize_filename as sanitize_filename

class Artist:
    def __init__(self, client, json_dict) -> None: ...
    def __len__(self): ...
    @property
    def name(self): ...
    @property
    def image_url(self): ...
    @property
    def songs(self): ...
    @property
    def num_songs(self): ...
    def add_song(self, new_song, verbose: bool = ..., include_features: bool = ...): ...
    def song(self, song_name): ...
    def to_json(self, filename: Incomplete | None = ..., sanitize: bool = ..., ensure_ascii: bool = ...): ...
    def to_text(self, filename: Incomplete | None = ..., binary_encoding: bool = ..., sanitize: bool = ...): ...
    def save_lyrics(self, filename: Incomplete | None = ..., extension: str = ..., overwrite: bool = ..., binary_encoding: bool = ..., ensure_ascii: bool = ..., sanitize: bool = ..., verbose: bool = ...) -> None: ...
