from _typeshed import Incomplete
from lyricsgenius.utils import sanitize_filename as sanitize_filename

class Song:
    def __init__(self, json_dict, lyrics: str = ...) -> None: ...
    @property
    def title(self): ...
    @property
    def artist(self): ...
    @property
    def lyrics(self): ...
    @property
    def album(self): ...
    @property
    def year(self): ...
    @property
    def url(self): ...
    @property
    def album_url(self): ...
    @property
    def featured_artists(self): ...
    @property
    def producer_artists(self): ...
    @property
    def media(self): ...
    @property
    def writer_artists(self): ...
    @property
    def song_art_image_url(self): ...
    def to_dict(self): ...
    def to_json(self, filename: Incomplete | None = ..., full_data: bool = ..., sanitize: bool = ..., ensure_ascii: bool = ...): ...
    def to_text(self, filename: Incomplete | None = ..., binary_encoding: bool = ..., sanitize: bool = ...): ...
    def save_lyrics(self, filename: Incomplete | None = ..., extension: str = ..., overwrite: Incomplete | None = ..., binary_encoding: bool = ..., ensure_ascii: bool = ..., full_data: bool = ..., sanitize: bool = ..., verbose: bool = ...) -> None: ...
    def __cmp__(self, other): ...
