from qdarktheme.qtpy import QtImportError as QtImportError
from qdarktheme.qtpy.qt_compat import QT_API as QT_API
from qdarktheme.util import OPERATORS as OPERATORS, compare_v as compare_v, get_logger as get_logger, get_qdarktheme_root_path as get_qdarktheme_root_path, multi_replace as multi_replace

class _SvgFileNotFoundError(FileNotFoundError): ...

def get_themes() -> tuple[str, ...]: ...
def load_stylesheet(theme: str = ..., border: str = ...) -> str: ...
def load_palette(theme: str = ...): ...
