import logging
from _typeshed import Incomplete
from pathlib import Path

OPERATORS: Incomplete

def multi_replace(target: str, replacements: dict[str, str]) -> str: ...
def get_logger(logger_name: str) -> logging.Logger: ...
def get_qdarktheme_root_path() -> Path: ...
def compare_v(v1: str, operator: str, v2: str) -> bool: ...
